name: fvastalpha
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  shared_preferences:
  flutter_polyline_points: ^0.1.0
  image_picker:  #DONE TODO configure for iOS later
  google_maps_flutter:   #DONE TODO configure for iOS later
  google_maps_webservice:   #DONE TODO configure for iOS later
  firebase_storage:
  firebase_core: ^0.4.0+9
  firebase_auth: ^0.14.0+5
  cloud_firestore:
  rave_flutter:   #DONE TODO configure the iOS version later
  geolocator:  #DONE TODO configure the iOS version later
  geocoder: ^0.2.1
  flutter_google_places: ^0.2.5
  intl:
  smooth_star_rating:
  solid_bottom_sheet: ^0.1.9
  eva_icons_flutter:
  flutter_svg:
  flutter_spinkit: ^4.1.2
  onesignal_flutter:
  url_launcher:
  cached_network_image:

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Geometria
      fonts:
        - asset: assets/fonts/Geometria.ttf
    - family: Raleway
      fonts:
        - asset: assets/fonts/raleway.ttf